version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: [
        "CMD-SHELL",
        "mongosh --eval \"try { rs.status() } catch (err) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }) }\""
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval '
      rs.initiate({
        _id: "rs0",
        members: [{ _id: 0, host: "mongodb:27017" }]
      });
      '

volumes:
  mongodb_data:
